<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Spect.Net.RomResources</RootNamespace>
    <AssemblyName>Spect.Net.RomResources</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Roms\**\*" />
  </ItemGroup>

</Project>
